spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://awseb-e-4wdwfpymf2-stack-awsebrdsdatabase-g3jwqpeupbrh.ceajyapu69b8.ap-northeast-2.rds.amazonaws.com:3306/?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  hibernate:
    ddl-auto: update


#jwt:
#  issuer: ${JWT_ISSUER}
#  secret_key: ${JWT_SECRET_KET}



